name: Version Bump

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!CHANGELOG.md'
      - '!package.json'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Check for changes
        id: check_changes
        run: |
          CHANGES=$(npx standard-version --dry-run | sed -n '/---/,/---/p' | sed '1d;$d')
          LINE_COUNT=$(echo "$CHANGES" | grep -c '^')
          if [ $LINE_COUNT -gt 1 ]; then
            echo "Bump version changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected, skipping version bump"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Set Git user
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "luciaaldana"
          git config --global user.email "luciaaldanacastillo@gmail.com"

      - name: Who am I?
        if: steps.check_changes.outputs.has_changes == 'true'
        run: git config --list

      - name: Bump version
        if: steps.check_changes.outputs.has_changes == 'true'
        run: npx standard-version

      - name: Set remote with token
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.OWNER_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Show remote URL
        if: steps.check_changes.outputs.has_changes == 'true'
        run: git remote -v

      - name: Probar acceso con token
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          curl -H "Authorization: token ${{ secrets.OWNER_TOKEN }}" https://api.github.com/user

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git push origin HEAD:main --follow-tags
