name: Version Bump

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!CHANGELOG.md'
      - '!package.json'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Check for changes
        id: check_changes
        run: |
          CHANGES=$(npx standard-version --dry-run | sed -n '/---/,/---/p' | sed '1d;$d')
          LINE_COUNT=$(echo "$CHANGES" | grep -c '^')
          if [ $LINE_COUNT -gt 1 ]; then
            echo "Bump version changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected, skipping version bump"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Set Git user
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "luciaaldana"
          git config --global user.email "luciaaldana@gmail.com"

      - name: Bump version
        if: steps.check_changes.outputs.has_changes == 'true'
        run: npx standard-version

      - name: Push version bump
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.OWNER_TOKEN }}
        run: |
          git config --global credential.helper ""
          git config --global user.name "luciaaldana"
          git config --global user.email "luciaaldana@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main --follow-tags
